// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ewcsr_sparse_cpp
Eigen::SparseMatrix<double> ewcsr_sparse_cpp(const Eigen::SparseMatrix<double>& mat, int num_threads);
RcppExport SEXP _celliverse_ewcsr_sparse_cpp(SEXP matSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(ewcsr_sparse_cpp(mat, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// filter_cluster_markers_cpp
List filter_cluster_markers_cpp(List pos_markers, List neg_markers, List med_markers);
RcppExport SEXP _celliverse_filter_cluster_markers_cpp(SEXP pos_markersSEXP, SEXP neg_markersSEXP, SEXP med_markersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pos_markers(pos_markersSEXP);
    Rcpp::traits::input_parameter< List >::type neg_markers(neg_markersSEXP);
    Rcpp::traits::input_parameter< List >::type med_markers(med_markersSEXP);
    rcpp_result_gen = Rcpp::wrap(filter_cluster_markers_cpp(pos_markers, neg_markers, med_markers));
    return rcpp_result_gen;
END_RCPP
}
// gini_rows_matrix
NumericVector gini_rows_matrix(IntegerVector i, IntegerVector p, NumericVector x, int m, int n);
RcppExport SEXP _celliverse_gini_rows_matrix(SEXP iSEXP, SEXP pSEXP, SEXP xSEXP, SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(gini_rows_matrix(i, p, x, m, n));
    return rcpp_result_gen;
END_RCPP
}
// gini_rows_lg_matrix
NumericVector gini_rows_lg_matrix(IntegerVector i, IntegerVector p, LogicalVector x, int m, int n);
RcppExport SEXP _celliverse_gini_rows_lg_matrix(SEXP iSEXP, SEXP pSEXP, SEXP xSEXP, SEXP mSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(gini_rows_lg_matrix(i, p, x, m, n));
    return rcpp_result_gen;
END_RCPP
}
// gini_rows_freq_mat
NumericVector gini_rows_freq_mat(NumericMatrix mat);
RcppExport SEXP _celliverse_gini_rows_freq_mat(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(gini_rows_freq_mat(mat));
    return rcpp_result_gen;
END_RCPP
}
// gini_rows_lg_marker_matrix
NumericVector gini_rows_lg_marker_matrix(IntegerVector i, IntegerVector p, LogicalVector x, int m, int n, CharacterVector names);
RcppExport SEXP _celliverse_gini_rows_lg_marker_matrix(SEXP iSEXP, SEXP pSEXP, SEXP xSEXP, SEXP mSEXP, SEXP nSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(gini_rows_lg_marker_matrix(i, p, x, m, n, names));
    return rcpp_result_gen;
END_RCPP
}
// jaccard_sparse_cpp_serial
S4 jaccard_sparse_cpp_serial(S4 mat);
RcppExport SEXP _celliverse_jaccard_sparse_cpp_serial(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_sparse_cpp_serial(mat));
    return rcpp_result_gen;
END_RCPP
}
// jaccard_sparse_cpp_multi_thread
S4 jaccard_sparse_cpp_multi_thread(S4 mat, int num_threads);
RcppExport SEXP _celliverse_jaccard_sparse_cpp_multi_thread(SEXP matSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(jaccard_sparse_cpp_multi_thread(mat, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// matrix_to_vector_na_omit
SEXP matrix_to_vector_na_omit(SEXP mat);
RcppExport SEXP _celliverse_matrix_to_vector_na_omit(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_to_vector_na_omit(mat));
    return rcpp_result_gen;
END_RCPP
}
// sparse_compare_threshold
SEXP sparse_compare_threshold(SEXP mat, std::string op, double threshold, bool zero_to_false);
RcppExport SEXP _celliverse_sparse_compare_threshold(SEXP matSEXP, SEXP opSEXP, SEXP thresholdSEXP, SEXP zero_to_falseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_to_false(zero_to_falseSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_compare_threshold(mat, op, threshold, zero_to_false));
    return rcpp_result_gen;
END_RCPP
}
// sparse_compare_threshold_same_ipx
SEXP sparse_compare_threshold_same_ipx(SEXP mat, std::string op, double threshold, bool zero_to_false);
RcppExport SEXP _celliverse_sparse_compare_threshold_same_ipx(SEXP matSEXP, SEXP opSEXP, SEXP thresholdSEXP, SEXP zero_to_falseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< std::string >::type op(opSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_to_false(zero_to_falseSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_compare_threshold_same_ipx(mat, op, threshold, zero_to_false));
    return rcpp_result_gen;
END_RCPP
}
// sparse_between_thresholds
SEXP sparse_between_thresholds(SEXP mat, double lower_threshold, double upper_threshold, bool zero_to_false);
RcppExport SEXP _celliverse_sparse_between_thresholds(SEXP matSEXP, SEXP lower_thresholdSEXP, SEXP upper_thresholdSEXP, SEXP zero_to_falseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type lower_threshold(lower_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type upper_threshold(upper_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_to_false(zero_to_falseSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_between_thresholds(mat, lower_threshold, upper_threshold, zero_to_false));
    return rcpp_result_gen;
END_RCPP
}
// sparse_between_thresholds_same_ipx
SEXP sparse_between_thresholds_same_ipx(SEXP mat, double lower_threshold, double upper_threshold, bool zero_to_false);
RcppExport SEXP _celliverse_sparse_between_thresholds_same_ipx(SEXP matSEXP, SEXP lower_thresholdSEXP, SEXP upper_thresholdSEXP, SEXP zero_to_falseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type lower_threshold(lower_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type upper_threshold(upper_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type zero_to_false(zero_to_falseSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_between_thresholds_same_ipx(mat, lower_threshold, upper_threshold, zero_to_false));
    return rcpp_result_gen;
END_RCPP
}
// sparse_row_nonzero_count_cpp
LogicalVector sparse_row_nonzero_count_cpp(S4 sp_mat, int noise_thresh);
RcppExport SEXP _celliverse_sparse_row_nonzero_count_cpp(SEXP sp_matSEXP, SEXP noise_threshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type sp_mat(sp_matSEXP);
    Rcpp::traits::input_parameter< int >::type noise_thresh(noise_threshSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_row_nonzero_count_cpp(sp_mat, noise_thresh));
    return rcpp_result_gen;
END_RCPP
}
// replace_na_with_zero_cpp
Rcpp::S4 replace_na_with_zero_cpp(Rcpp::S4 mat, int num_threads);
RcppExport SEXP _celliverse_replace_na_with_zero_cpp(SEXP matSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(replace_na_with_zero_cpp(mat, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// compute_centroids_cpp
Rcpp::NumericMatrix compute_centroids_cpp(Rcpp::S4 mat, Rcpp::CharacterVector sketched_clusters, Rcpp::CharacterVector unique_clusters, int num_threads);
RcppExport SEXP _celliverse_compute_centroids_cpp(SEXP matSEXP, SEXP sketched_clustersSEXP, SEXP unique_clustersSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sketched_clusters(sketched_clustersSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type unique_clusters(unique_clustersSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_centroids_cpp(mat, sketched_clusters, unique_clusters, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// sparse_dense_correlation_cpp
Eigen::MatrixXd sparse_dense_correlation_cpp(Rcpp::S4 sp_mat, Rcpp::NumericMatrix centroids, int num_threads);
RcppExport SEXP _celliverse_sparse_dense_correlation_cpp(SEXP sp_matSEXP, SEXP centroidsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::S4 >::type sp_mat(sp_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type centroids(centroidsSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_dense_correlation_cpp(sp_mat, centroids, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// compute_reduced_centroids_cpp
Rcpp::NumericMatrix compute_reduced_centroids_cpp(Rcpp::NumericMatrix mat, Rcpp::CharacterVector sketched_clusters, Rcpp::CharacterVector unique_clusters, int num_threads);
RcppExport SEXP _celliverse_compute_reduced_centroids_cpp(SEXP matSEXP, SEXP sketched_clustersSEXP, SEXP unique_clustersSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type sketched_clusters(sketched_clustersSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type unique_clusters(unique_clustersSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_reduced_centroids_cpp(mat, sketched_clusters, unique_clusters, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// mutual_rank_sparse_cpp
S4 mutual_rank_sparse_cpp(S4 mat, int num_threads);
RcppExport SEXP _celliverse_mutual_rank_sparse_cpp(SEXP matSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(mutual_rank_sparse_cpp(mat, num_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_celliverse_ewcsr_sparse_cpp", (DL_FUNC) &_celliverse_ewcsr_sparse_cpp, 2},
    {"_celliverse_filter_cluster_markers_cpp", (DL_FUNC) &_celliverse_filter_cluster_markers_cpp, 3},
    {"_celliverse_gini_rows_matrix", (DL_FUNC) &_celliverse_gini_rows_matrix, 5},
    {"_celliverse_gini_rows_lg_matrix", (DL_FUNC) &_celliverse_gini_rows_lg_matrix, 5},
    {"_celliverse_gini_rows_freq_mat", (DL_FUNC) &_celliverse_gini_rows_freq_mat, 1},
    {"_celliverse_gini_rows_lg_marker_matrix", (DL_FUNC) &_celliverse_gini_rows_lg_marker_matrix, 6},
    {"_celliverse_jaccard_sparse_cpp_serial", (DL_FUNC) &_celliverse_jaccard_sparse_cpp_serial, 1},
    {"_celliverse_jaccard_sparse_cpp_multi_thread", (DL_FUNC) &_celliverse_jaccard_sparse_cpp_multi_thread, 2},
    {"_celliverse_matrix_to_vector_na_omit", (DL_FUNC) &_celliverse_matrix_to_vector_na_omit, 1},
    {"_celliverse_sparse_compare_threshold", (DL_FUNC) &_celliverse_sparse_compare_threshold, 4},
    {"_celliverse_sparse_compare_threshold_same_ipx", (DL_FUNC) &_celliverse_sparse_compare_threshold_same_ipx, 4},
    {"_celliverse_sparse_between_thresholds", (DL_FUNC) &_celliverse_sparse_between_thresholds, 4},
    {"_celliverse_sparse_between_thresholds_same_ipx", (DL_FUNC) &_celliverse_sparse_between_thresholds_same_ipx, 4},
    {"_celliverse_sparse_row_nonzero_count_cpp", (DL_FUNC) &_celliverse_sparse_row_nonzero_count_cpp, 2},
    {"_celliverse_replace_na_with_zero_cpp", (DL_FUNC) &_celliverse_replace_na_with_zero_cpp, 2},
    {"_celliverse_compute_centroids_cpp", (DL_FUNC) &_celliverse_compute_centroids_cpp, 4},
    {"_celliverse_sparse_dense_correlation_cpp", (DL_FUNC) &_celliverse_sparse_dense_correlation_cpp, 3},
    {"_celliverse_compute_reduced_centroids_cpp", (DL_FUNC) &_celliverse_compute_reduced_centroids_cpp, 4},
    {"_celliverse_mutual_rank_sparse_cpp", (DL_FUNC) &_celliverse_mutual_rank_sparse_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_celliverse(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
