# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ewcsr_sparse_cpp <- function(mat, num_threads = -1L) {
    .Call(`_celliverse_ewcsr_sparse_cpp`, mat, num_threads)
}

filter_cluster_markers_cpp <- function(pos_markers, neg_markers, med_markers) {
    .Call(`_celliverse_filter_cluster_markers_cpp`, pos_markers, neg_markers, med_markers)
}

gini_rows_matrix <- function(i, p, x, m, n) {
    .Call(`_celliverse_gini_rows_matrix`, i, p, x, m, n)
}

gini_rows_lg_matrix <- function(i, p, x, m, n) {
    .Call(`_celliverse_gini_rows_lg_matrix`, i, p, x, m, n)
}

gini_rows_freq_mat <- function(mat) {
    .Call(`_celliverse_gini_rows_freq_mat`, mat)
}

gini_rows_lg_marker_matrix <- function(i, p, x, m, n, names = character()) {
    .Call(`_celliverse_gini_rows_lg_marker_matrix`, i, p, x, m, n, names)
}

jaccard_sparse_cpp_serial <- function(mat) {
    .Call(`_celliverse_jaccard_sparse_cpp_serial`, mat)
}

jaccard_sparse_cpp_multi_thread <- function(mat, num_threads = -1L) {
    .Call(`_celliverse_jaccard_sparse_cpp_multi_thread`, mat, num_threads)
}

matrix_to_vector_na_omit <- function(mat) {
    .Call(`_celliverse_matrix_to_vector_na_omit`, mat)
}

sparse_compare_threshold <- function(mat, op, threshold, zero_to_false = TRUE) {
    .Call(`_celliverse_sparse_compare_threshold`, mat, op, threshold, zero_to_false)
}

sparse_compare_threshold_same_ipx <- function(mat, op, threshold, zero_to_false = TRUE) {
    .Call(`_celliverse_sparse_compare_threshold_same_ipx`, mat, op, threshold, zero_to_false)
}

sparse_between_thresholds <- function(mat, lower_threshold, upper_threshold, zero_to_false = TRUE) {
    .Call(`_celliverse_sparse_between_thresholds`, mat, lower_threshold, upper_threshold, zero_to_false)
}

sparse_between_thresholds_same_ipx <- function(mat, lower_threshold, upper_threshold, zero_to_false = TRUE) {
    .Call(`_celliverse_sparse_between_thresholds_same_ipx`, mat, lower_threshold, upper_threshold, zero_to_false)
}

sparse_row_nonzero_count_cpp <- function(sp_mat, noise_thresh) {
    .Call(`_celliverse_sparse_row_nonzero_count_cpp`, sp_mat, noise_thresh)
}

replace_na_with_zero_cpp <- function(mat, num_threads = -1L) {
    .Call(`_celliverse_replace_na_with_zero_cpp`, mat, num_threads)
}

compute_centroids_cpp <- function(mat, sketched_clusters, unique_clusters, num_threads = -1L) {
    .Call(`_celliverse_compute_centroids_cpp`, mat, sketched_clusters, unique_clusters, num_threads)
}

sparse_dense_correlation_cpp <- function(sp_mat, centroids, num_threads = -1L) {
    .Call(`_celliverse_sparse_dense_correlation_cpp`, sp_mat, centroids, num_threads)
}

compute_reduced_centroids_cpp <- function(mat, sketched_clusters, unique_clusters, num_threads = -1L) {
    .Call(`_celliverse_compute_reduced_centroids_cpp`, mat, sketched_clusters, unique_clusters, num_threads)
}

mutual_rank_sparse_cpp <- function(mat, num_threads = -1L) {
    .Call(`_celliverse_mutual_rank_sparse_cpp`, mat, num_threads)
}

